# Generated by Django 5.0.2 on 2024-03-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_post_tags_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
